version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_AUTH=mongodb://mongodb:27017/auth_db
      - PORT=3001
      - JWT_SECRET=cesi_vents_backend_2025

  club-service:
    build: ./club-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_CLUB=mongodb://mongodb:27017/club_db
      - PORT=3002
      - JWT_SECRET=cesi_vents_backend_2025

  event-service:
    build: ./event-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_EVENT=mongodb://mongodb:27017/event_db
      - PORT=3003
      - JWT_SECRET=cesi_vents_backend_2025

  ticket-service:
    build: ./ticket-service
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_TICKET=mongodb://mongodb:27017/ticket_db
      - PORT=3004
      - JWT_SECRET=cesi_vents_backend_2025

  gamification-service:
    build: ./gamification-service
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_GAMIFICATION=mongodb://mongodb:27017/gamification_db
      - PORT=3005
      - JWT_SECRET=cesi_vents_backend_2025

  bde_membership-service:
    build: ./bde_membership-service
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI_BDE_MEMBERSHIP=mongodb://mongodb:27017/bde_membership_db
      - PORT=3006
      - JWT_SECRET=cesi_vents_backend_2025

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - club-service
      - event-service
      - ticket-service
      - gamification-service
      - bde_membership-service

volumes:
  mongodb_data:
