version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - event-service
      - ticket-service
      - gamification-service
      - club-service
      - bde_membership-service
      - promotion-service
      - transaction-service
    environment:
      - PORT=3000

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth_db
      - PORT=3001
      - JWT_SECRET=cesi_vents_backend_2025

  event-service:
    build: ./event-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/events_db
      - PORT=3002
      - JWT_SECRET=cesi_vents_backend_2025

  ticket-service:
    build: ./ticket-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tickets_db
      - PORT=3003
      - JWT_SECRET=cesi_vents_backend_2025

  gamification-service:
    build: ./gamification-service
    ports:
      - "3004:3004"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gamification_db
      - PORT=3004
      - JWT_SECRET=cesi_vents_backend_2025

  club-service:
    build: ./club-service
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
      - auth-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/clubs_db
      - PORT=3005
      - JWT_SECRET=cesi_vents_backend_2025
      - AUTH_SERVICE_URL=http://auth-service:3001

  bde_membership-service:
    build: ./bde_membership-service
    ports:
      - "3006:3006"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/bde_membership_db
      - PORT=3006
      - JWT_SECRET=cesi_vents_backend_2025

  promotion-service:
    build: ./promotion-service
    ports:
      - "3007:3007"
    depends_on:
      - mongodb
      - auth-service
      - club-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/promotion_db
      - PORT=3007
      - JWT_SECRET=cesi_vents_backend_2025
      - AUTH_SERVICE_URL=http://auth-service:3001
      - CLUB_SERVICE_URL=http://club-service:3005

  transaction-service:
    build: ./transaction-service
    ports:
      - "3008:3008"
    depends_on:
      - mongodb
      - auth-service
      - event-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/transaction_db
      - PORT=3008
      - JWT_SECRET=cesi_vents_backend_2025
      - AUTH_SERVICE_URL=http://auth-service:3001
      - EVENT_SERVICE_URL=http://event-service:3002

volumes:
  mongodb_data:
